# Generated by Django 5.1 on 2025-02-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_bn',
            field=models.TextField(blank=True, null=True, verbose_name='Answer (Bengali)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_hi',
            field=models.TextField(blank=True, null=True, verbose_name='Answer (Hindi)'),
        ),
    ]
